# Generated by Django 4.2 on 2023-05-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layertypesmodel',
            old_name='name',
            new_name='name_1',
        ),
        migrations.AddField(
            model_name='layertypesmodel',
            name='name_2',
            field=models.CharField(default='', max_length=240),
        ),
    ]
