# Generated by Django 4.2 on 2023-05-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_featurecitymodel_layertypesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectormodel',
            name='data_date',
            field=models.DateTimeField(null=True),
        ),
    ]
