# Generated by Django 4.2 on 2023-05-02 23:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_delete_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectormodel',
            name='data',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Vector data'),
        ),
    ]
