# Generated by Django 4.2 on 2023-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_rename_name_layertypesmodel_name_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuremodel',
            old_name='name',
            new_name='name_1',
        ),
        migrations.RenameField(
            model_name='layertypesmodel',
            old_name='name_1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='layertypesmodel',
            name='name_2',
        ),
        migrations.AddField(
            model_name='featuremodel',
            name='name_2',
            field=models.CharField(default=''),
        ),
    ]
