# Generated by Django 4.2 on 2023-05-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_featuretypemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectormodel',
            name='bounds',
        ),
    ]
