# Generated by Django 4.2 on 2023-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_rename_name_featuremodel_name_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuremodel',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='majority',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='median',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='minority',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='range',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='stdev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='sum',
            field=models.FloatField(null=True),
        ),
    ]
