# Generated by Django 4.2 on 2023-05-28 00:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_remove_vectormodel_bounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('properties', models.JSONField()),
                ('name', models.CharField()),
                ('count', models.IntegerField()),
                ('sum', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('st_dev', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('range', models.FloatField()),
                ('minority', models.FloatField()),
                ('majority', models.FloatField()),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.vectormodel')),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureTypeModel',
        ),
    ]
