# Generated by Django 4.2 on 2023-06-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_featuremodel_count_alter_featuremodel_majority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectormodel',
            name='mean_sum',
            field=models.IntegerField(default=0),
        ),
    ]
