# Generated by Django 4.2 on 2023-05-28 00:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_featuremodel_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuremodel',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
