# Generated by Django 4.2 on 2023-06-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_vectormodel_mean_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectormodel',
            name='mean_sum',
        ),
    ]
