# Generated by Django 4.2 on 2023-05-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_featuremodel_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuremodel',
            name='count',
            field=models.FloatField(),
        ),
    ]
