# Generated by Django 4.2 on 2023-05-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_alter_featuremodel_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuremodel',
            old_name='st_dev',
            new_name='stdev',
        ),
    ]
