# Generated by Django 4.2 on 2023-06-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0006_remove_vectormodel_mean_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointMLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geogson_file', models.FileField(upload_to='clustered_points/')),
                ('point_models', models.ManyToManyField(to='geo.pointmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson_str', models.TextField()),
                ('name', models.CharField()),
                ('vector_model', models.ManyToManyField(to='geo.vectormodel')),
            ],
        ),
    ]
