# Generated by Django 4.1.7 on 2023-04-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=240, verbose_name='file_name')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('type', models.CharField(choices=[('PT', 'Point'), ('RT', 'Raster'), ('VT', 'Vector')], default='PT', max_length=2)),
            ],
        ),
    ]
